config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/home'
  get 'pages/not_authorised'
  get 'pages/login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.email = auth['info']['email']
      user.name = auth['info']['name']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: 'public/404.html', status: not_found
    end
  end

  private
  
  def valid_page?
    template_exists? "pages/#{params[:page]}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>CheckinApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
 <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"
      crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

        <body>
          <div class="container-fluid" id="main">
            <nav class="navbar navbar-fluid navbar-expand-lg navbar-dark bg-primary">

              <%= link_to  (image_tag  "logo.png", width: '30px'), class: 'navbar-brand' %>
                <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                  aria-expanded="false" aria-label="Toggle navigation"></button>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                  <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active"><%= link_to  "Home", pages_home_path, class: 'nav-link' %></li>
                    <li class="nav-item"><%= link_to  "Check In", pages_login_path , class: 'nav-link' %></li>
                  </ul>
                </div>
            </nav>

            <%= yield %>

          </div>
          <!-- Optional JavaScript -->
          <!-- jQuery first, then Popper.js, then Bootstrap JS -->
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>
        </body>

</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/docs.html.erb
<% provide(:title, "Docs") %>
<h1>Documents</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="display-3">Welcome to the CheckIn App</h1>
  <p class="lead">Use this app to see what CheckIn knows about you</p>
  <hr class="my-2">
  <p class="lead">
  <%= link_to  "Log In",pages_login_path, class: "btn btn-primary btn-lg" , role: 'button' %>
    <a class="btn btn-link" type="button" href="">Read about it</a>
  </p>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/login.html.erb
<h1>Pages#login</h1>
<p>Find me in app/views/pages/login.html.erb</p>

app/views/pages/not_authorised.html.erb
<h1>Pages#not_authorised</h1>
<p>Find me in app/views/pages/not_authorised.html.erb</p>